### PR TITLE
Improve grammar and robustness and fix drill, see shellcheck.net

### PR DESCRIPTION
**Pull request by graysky2**
- Mixed tabs/spaces all spaces
- https://github.com/koalaman/shellcheck/wiki/SC2002
- https://github.com/koalaman/shellcheck/wiki/SC2006
- https://github.com/koalaman/shellcheck/wiki/SC2086

### CODE REVIEW

**Comment by thomasmerz** [comment]
Also fixed by newer PR #68 - so we might close this one?! @cleanbrowsing + @graysky2

**Comment by thomasmerz** [comment]
@graysky2 , did you oversee my update regarding my newer PR? 🤔

**Comment by graysky2** [comment]
Nope, it is unclear that upstream has an interest in this any more.

**Comment by graysky2** [comment]
@thomasmerz - your PR does not fix https://github.com/cleanbrowsing/dnsperftest/issues/76

**Comment by thomasmerz** [comment]
> Nope, it is unclear that upstream has an interest in this any more.

What a pity 😢 I wrote some emails directly to the maintainer, but without success as we can see…

**Comment by graysky2** [comment]
It's fine, one source becomes stable a new fork become active

**Comment by thomasmerz** [comment]
Yeah, but do you know a new **active** fork yet? 🤔

**Pull request closed without merging**
